---
name: CI
on:
  push:

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          load: false
          push: false # DO NOT SET TO TRUE!
          tags: ghcr.io/${{ github.repository }}:commit-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
